language: node_js
node_js:
    - '0.10'
branches:
  only:
    - master
before_script: 
    - 'npm install wintersmith -g'
script:
    - 'rm -rf ./build && wintersmith build'
after_success:
    'cd build && find ./ -type f -exec curl -u $FTP_USER:$FTP_PASS --ftp-create-dirs -T {} ftp://freezeultimate.com/{} \;'
